### ISSUE TITLE
TypeScript 2.2 update

### ISSUE THREAD

**Issue by RomkeVdMeulen** [Everlaw/nbts#101]
I'm getting errors in the Netbeans error that aren't a problem for the compiler. Types related to the fetch API aren't found. Probable the current build of the plugin has an outdated version of the standard lib - the fetch API was only added in 2.2.1.

Any idea when the next release with updated standard lib might be?

**Comment by Rycochet** [comment]
Might be wroth changing the title to something like "TypeScript 2.2 update" - NBTS uses a bundled version for various code reasons - but I'm hoping that TS starts providing enough in the service that it can shift to using whichever version you supply (above whatever version gets it) :-)

**Comment by jeffrey-easyesi** [comment]
Updated to 2.3.

**Comment by RomkeVdMeulen** [comment]
Great. Thank you!
