### ISSUE TITLE
Debugging features / breakpoints

### ISSUE THREAD

**Issue by ManfredSteiner** [Everlaw/nbts#104]
When I am using Typscript on Netbeans, I am missing any debugging support. I cannot find find any possibility to set breakpoints or to step code. If I start a debugging session, it jumps on start of the transpiled file.

Are there any additional modules available for debugging on typescript level?
Will there come any improvements in the near future?

**Comment by Chris2011** [comment]
There is no debugging functionality for TS atm. See this ticket here: #9 so please close this ticket and comment to the other one and vote for it.

**Comment by ManfredSteiner** [comment]
Issue covered by #9
