### ISSUE TITLE
TypeScript IntelliSense Very Slow

### ISSUE THREAD

**Issue by JeSuisAlrick** [Everlaw/nbts#106]
It seems error checking is a bit excessive and this is causing IntelliSense to be very slow.

My main observation is that node_modules folder is being checked for errors every time a file is changed.

Can you provide some options to limit how frequently checks are done, or rather, exclude node_modules from the routine checks? I'd assume that the node_modules folder should only be checked once per project start-up unless the packages.json file has changed.

Thanks

**Comment by Chris2011** [comment]
The node_modules folder should never be checked because those are not your dependencies and they are packages only for using. @JeSuisAlrick  So please exclude the node_modules folder in the options under options -> miscellaneous -> files -> Files ignored by the ide.

**Comment by Chris2011** [comment]
The same you should do with bower_components.

**Comment by JeSuisAlrick** [comment]
Your solution worked. Thanks :+1:
