### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by geekdenz** [Everlaw/nbts#11]
Refactoring currently doesn't work. Would be another great feature to have. Rename etc.

**Comment by jeffrey-easyesi** [comment]
You can currently rename with Ctrl-R, although it's limited to changing occurrences in the current file. Full rename support is coming soon.

**Comment by jeffrey-easyesi** [comment]
Fully-featured rename is now implemented.

**Comment by geekdenz** [comment]
Awesome! Can't wait to check it out.

**Comment by geekdenz** [comment]
Confirm it's working well! Good work!
