### ISSUE TITLE
Failure to scan tsconfig and other file

### ISSUE THREAD

**Issue by jGauravGupta** [Everlaw/nbts#114]
If file like tsconfig.json, proxy.conf.json, postcss.config.json, package.json, tsconfig-aot.json, tslint.json, .angular-cli.json, webpack etc available in NetBeans Maven Web Application project root instead of src/main/webapp folder then ts file showing error.

**Project View :**
![11](https://user-images.githubusercontent.com/15934072/28335308-9791609c-6c1b-11e7-9ed1-5ff5a1442f92.PNG)

**File View :**
![22](https://user-images.githubusercontent.com/15934072/28335309-979733f0-6c1b-11e7-956f-6792752b07ad.PNG)

Sample Project to reproduce the issue : https://drive.google.com/file/d/0B8lO89ZjkGhQYS1COXNtcDRhamc/view

**Comment by jeffrey-easyesi** [comment]
tsconfig.json currently has to be under a source root: https://github.com/Everlaw/nbts/issues/21

**Comment by jGauravGupta** [comment]
Can you please provide the support . Code generator tool like jHipster [ [sample app](https://github.com/jhipster/jhipster-sample-app-ng2) ] or Jeddict generates the tsconfig.json inside project root folder.

**Comment by jeffrey-easyesi** [comment]
right now nbts assumes that one NetBeans source root = one TS project. I need to decouple these concepts to allow for other layouts like multiple TS projects under one source root, or one TS project across all source roots with tsconfig.json at the NetBeans project root. It'll take some significant rearchitecting though.

**Comment by jGauravGupta** [comment]
I am representing NetBeans IDE ( + Java EE ) tooling in JavaOne Conf (1st Oct)  this year so if this feature is not feasible in this time frame.  Can you please provide the feature to disable error icon from ts file . As NetBeans IDE already have support for js or html file to disable error icon.

**Comment by Chris2011** [comment]
@jGauravGupta maybe the new release 2.5.3.0 could be solve your problem?
