### ISSUE TITLE
Please support the angular2 template syntax

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#118]
I don't know whether it is in your scope or not, but HTML files can't handle the new angular2 template syntax like  [my-attribute], (property) or *smth. See the screenshot for what I mean:

![angular2-template-syntax](https://user-images.githubusercontent.com/795658/29029904-8baceb0c-7b89-11e7-8563-c8729b8185d7.png)

As you can see the file has errors, I deactivated the error checking for html filex, but there are still errors, because those things are new to the HTML lexer I think.

Regards

Chris

**Comment by jeffrey-easyesi** [comment]
HTML highlighting is part of the NetBeans project, it has nothing to do with this plugin or with TypeScript.

**Comment by Chris2011** [comment]
yeah, as I thought. Thx.
