### ISSUE TITLE
Implement all abstract methods

### ISSUE THREAD

**Issue by geekdenz** [Everlaw/nbts#12]
When creating an interface or an abstract class, it would be great if one could click the hint and implement all abstract methods which throw an Error like they throw an exception in Java.

**Comment by clicman** [comment]
+1

**Comment by dipacs** [comment]
+1

**Comment by dbiagi** [comment]
+1

**Comment by danielschmitz** [comment]
:+1:

**Comment by alihammad-gist** [comment]
+1

**Comment by jeffrey-easyesi** [comment]
"Quick fix" functionality like this is something that belongs in the TypeScript language service, so that all plugins based on that could use it.

See: https://github.com/Microsoft/TypeScript/issues/6943

**Comment by jeffrey-easyesi** [comment]
This has been implemented in the TypeScript project and will be in version 2.2: https://github.com/Microsoft/TypeScript/pull/11547
