### ISSUE TITLE
Please update to 2.6.1

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#125]
Please change version to 2.6.1. It will add this new quick fix feature for npm install a missing @type definition: https://github.com/Microsoft/TypeScript/issues/14423

And some other stuff.

Cheers

Chris

**Comment by Chris2011** [comment]
Now we have 2.7.3 I think and we are close to 2.8. What is the state of the plugin?

**Comment by Rycochet** [comment]
The plugin works perfectly with the latest versions of TS - just make sure you `npm install --save typescript` and it'll use whichever one you have next to it.

There's no need for them to release a new version just to bump the version number when there's literally no other changes needed as the TS service handles nearly everything directly.

**Comment by jeffrey-easyesi** [comment]
@Rycochet: Actually nbts has its own internal copy of TypeScript; currently it can't use an external TS installation.

I've just released a new version based on TS 2.7.2.

**Comment by Rycochet** [comment]
@jeffrey-easyesi Doh - don't know where I thought it could use an external one!
