### ISSUE TITLE
Provide options for auto format / align rules with VSCode

### ISSUE THREAD

**Issue by simdevmon** [Everlaw/nbts#127]
It would be nice if I could configure rules for auto formatting. 

For example imports are formatted like this
`import {Component, OnInit} from '@angular/core';`

An option to have whitespaces like the default formatting in Visual Studio Code would be good, that the same formatting rules can be applied across different IDEs.
`import { Component, OnInit } from '@angular/core';`

**Comment by Chris2011** [comment]
This is a duplicate of: #74 and #81. Thx.
