### ISSUE TITLE
Support for local install of Typescript

### ISSUE THREAD

**Issue by Rycochet** [Everlaw/nbts#133]
Although this has an internal copy of the Typescript install, it would be nice if it could find an installed copy and use it instead, in a way not dissimilar to the finding of `tsconfig.json`.

Currently the release version number is the same as the TS version included, but if you could install a different version the the source code compilation would be using the same version as the TS service that is providing support to NetBeans. I don't know if there would be any compatibility issues, but by locking the same Major version of TS should prevent anything big from going wrong.

It might still call for new builds if there are incompatible updates in TS, although that would hopefully be in the language spec, and not the TS service itself.

Referenced in #125

**Comment by jeffrey-easyesi** [comment]
This has now been implemented in nbts version 3.0.0: nbts now uses an external, user-specified TS installation. I've tested that basic functionality works with TS 3.0-rc and various versions all the way back to TS 1.5.3.

**Comment by RomkeVdMeulen** [comment]
Nice work!
