### ISSUE TITLE
Toggle comments on .ts files

### ISSUE THREAD

**Issue by maxidirienzo** [Everlaw/nbts#138]
Don't know if this applies to the plugin, but the toggle comment (Ctrl+Shift+C) doesn't works on .ts files, would be nice to have this working.

**Comment by RKaczmarek** [comment]
no problem with this

**Comment by jeffrey-easyesi** [comment]
Works for me using either Ctrl+Shift+C, Ctrl+Slash, or "<ins>S</ins>ource" > "Toggle Co<ins>m</ins>ment" in the menu...

**Comment by maxidirienzo** [comment]
I've re- mapped the shortcut and it's working!
The strange thing is that the shortcut worked for html/php/js files but not on TS.
Thanks for the feedback!
