### ISSUE TITLE
Typescript lib directory is not set

### ISSUE THREAD

**Issue by programster** [Everlaw/nbts#150]
How do I resolve this error in Netbeans 11 after having installed the latest typescript plugin (3.0.1)?

>Typescript lib directory not set

![Workspace 1_001](https://user-images.githubusercontent.com/5709838/59217215-5a30cd80-8bb5-11e9-916c-4c8c307fa7eb.png)

When I go to plugins, I don't even see the typescript one to configure...

![Selection_002](https://user-images.githubusercontent.com/5709838/59217250-6cab0700-8bb5-11e9-8368-61007074458a.png)

There doesn't appear to be a typescript area under project settings...

![Selection_003](https://user-images.githubusercontent.com/5709838/59217288-84828b00-8bb5-11e9-979e-3c580f9b11f1.png)

... not did I see anywhere to configure Typescript under tools > options.

![Options_004](https://user-images.githubusercontent.com/5709838/59217335-9f54ff80-8bb5-11e9-8901-e0166fd225a9.png)

Any help/advice appreciated.

**Comment by jeffrey-easyesi** [comment]
Right click inside the editor window of a .ts file:

![image](https://user-images.githubusercontent.com/3847609/59217769-8b88a980-8b73-11e9-9b05-ca44dc874c01.png)

**Comment by programster** [comment]
:man_facepalming:  so simple
Thanks.

**Comment by Chris2011** [comment]
This is what I said here: #140 people expect such behaviour inside the project properties and/or in the global options. Not inside a single TS file which doesn't make sense at all. Seems simple but it is not where you expect it.
