### ISSUE TITLE
[Question]: license of the typescript image for *.ts files

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#151]
Hey @jamie-everlaw or @jeffrey-easyesi or whoever, plese tell me, what the license of this image is: https://github.com/Everlaw/nbts/blob/master/src/netbeanstypescript/resources/typescript.png

Thx :)

**Comment by jeffrey-easyesi** [comment]
It's just an edit of NetBeans 8.0.2's JS icon and may be used under the terms of the CDDL version 1.0 and/or the GPL version 2.0 with Classpath Exception.

**Comment by Chris2011** [comment]
Thx :)
