### ISSUE TITLE
Syntax Highlighting Improvement: /// <reference path="./typings/tsd.d.ts" />

### ISSUE THREAD

**Issue by geekdenz** [Everlaw/nbts#18]
Since the above is a special comment, I think a nice to have and probably easy change is to have a special coloring that is not a comment for this.

**Comment by geekdenz** [comment]
Are you using ANTLR or another tool to do lexers etc.? If yes, would you mind providing the ANTLR source file that you are using?

**Comment by jeffrey-easyesi** [comment]
Unfortunately, TypeScript does not include special comments in the AST. Here is the function that parses special comments: https://github.com/Microsoft/TypeScript/blob/v1.6.2/src/compiler/parser.ts#L5194 Note that the location of a special comment is not saved anywhere (unless there's an error).

To highlight these comments I would have to either modify or duplicate this code, either of which is easy to do but creates a potential ongoing maintenance burden when updating to new versions of TypeScript. I would prefer not to add more perpetual maintenance costs unless the benefit is very large.

**Comment by geekdenz** [comment]
OK, understand. Maybe not worth doing then.
