### ISSUE TITLE
TypeScript plugin cannot run Node.js

### ISSUE THREAD

**Issue by vt97john** [Everlaw/nbts#19]
When I create a typescript file, netbeans shows an error that says "Error creating Node.js process. Make sure the "nodejs" or "node" executables are in stalled and in your PATH."  I do have node in my path and I am able to run Javascript files as node modules within netbeans using a node plugin.  Here is my .bashrc:

echo prefix = ~/.node >> ~/.npmrc
export PATH=/usr/local/bin/.node/bin:$PATH
export PATH=/usr/local/bin/.node/lib:$PATH
export PATH=$PATH:/usr/local/bin

**Comment by mintern** [comment]
Are you on Linux? The desktop environment (which NetBeans inherits) doesn't read `~/.bashrc`, only Bash command lines. You'll want to instead change your `PATH` in `~/.profile`. After that, you'll have to log out and log back in for it to take effect.

**Comment by vt97john** [comment]
I'm on Mac

Sent from my iPhone

On Oct 26, 2015, at 5:45 PM, Brandon Mintern <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you on Linux? The desktop environment (which NetBeans inherits) doesn't read ~/.bashrc, only Bash command lines. You'll want to instead change your PATH in ~/.profile. After that, you'll have to log out and log back in for it to take effect.

**Comment by mintern** [comment]
The same caveat applies, then, but the solution is much more difficult. You have a few options:

1. Launch NetBeans from your Terminal so that it inherits the Terminal's `PATH`.
2. Run `launchctl setenv PATH $PATH` from the Terminal to set the `PATH` for Finder-launched applications to match the Terminal's `PATH`, then relaunch NetBeans from the Finder. This will not persist across reboots.
3. Research a bit on StackExchange ([this](https://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications) and [this](https://serverfault.com/questions/16355/how-to-set-global-path-on-os-x) might be a good start) to figure out the "right" way to permanently set the `PATH` for graphical applications.

Sorry if that's not helpful. I don't run Mac, so I'm not familiar with the standard way to set custom a `PATH` for GUI apps.

**Comment by mintern** [comment]
Note that we covered this a bit in #3. @jeffrey-easyesi added a fallback to `/usr/local/bin/node` to handle the default OSX `node` install location. If you're installing it to a custom location, though, you're going to have to figure out how to get the right `PATH` conveyed to NetBeans. Hopefully the previous comment helps!

@geekdenz [suggested using the HTML5 settings for nodejs executable](https://github.com/Everlaw/nbts/issues/3#issuecomment-147142232). We might want to do that in the future, which would allow you to explicitly set the `node` executable location from Tools&rarr;Options. Unfortunately, that won't be possible until NetBeans 8.1 is officially released.

**Comment by vt97john** [comment]
Thanks, i hate to keep coming back to you like a tech support hotline … but I do have the default node installation on my mac and I still get the error.

John T. Mallonee
Cell: 703-217-7673
Fax: 703.738.7444

Clearsoft Inc.
Software Engineering & Systems Integration
4000 Legato Road | Suite 1100 | Fairfax, VA 22033 |  www.clearsoftinc.com<http://www.clearsoftinc.com/>

PLEASE NOTE:  This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

On Oct 26, 2015, at 6:37 PM, Brandon Mintern <notifications@github.com<mailto:notifications@github.com>> wrote:


Note that we covered this a bit in #3<https://github.com/Everlaw/nbts/issues/3>. @jeffrey-easyesi<https://github.com/jeffrey-easyesi> added a fallback to /usr/local/bin/node to handle the default OSX node install location. If you're installing it to a custom location, though, you're going to have to figure out how to get the right PATH conveyed to NetBeans. Hopefully the previous comment helps!

@geekdenz<https://github.com/geekdenz> suggested using the HTML5 settings for nodejs executable<https://github.com/Everlaw/nbts/issues/3#issuecomment-147142232>. We might want to do that in the future, which would allow you to explicitly set the node executable location from Tools→Options. Unfortunately, that won't be possible until NetBeans 8.1 is officially released.

**Comment by mintern** [comment]
Sorry... I should have been clearer: #4 added the `/usr/local/bin/node` fallback, but we haven't yet made a release that includes that change.

For now, you can either build the plugin from source (@geekdenz made a [helpful video](https://youtu.be/OJn_RugJX-M) showing how), or you can use one of the methods I suggested above to make sure that NetBeans sees the correct `PATH`.

**Comment by geekdenz** [comment]
Hi @vt97john, Could you attach the output of
```
which node
which nodejs
```
from the terminal on your Mac?

**Comment by vt97john** [comment]
Johns-MacBook-Pro:~ John$ which node
/usr/local/bin/node
Johns-MacBook-Pro:~ John$ which nodejs
Johns-MacBook-Pro:~ John$




John T. Mallonee
Cell: 703-217-7673
Fax: 703.738.7444

Clearsoft Inc.
Software Engineering & Systems Integration
4000 Legato Road | Suite 1100 | Fairfax, VA 22033 |  www.clearsoftinc.com<http://www.clearsoftinc.com/>

PLEASE NOTE:  This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

On Oct 27, 2015, at 7:36 PM, Tim-Hinnerk Heuer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @vt97john<https://github.com/vt97john>, Could you attach the output of

which node
which nodejs


from the terminal on your Mac?

**Comment by geekdenz** [comment]
Mh, so that should be right then and working. Not sure why it won't for you. Can you execute NetBeans from a terminal:
```
/Applications/NetBeans/NetBeans\ 8.1\ RC.app/Contents/MacOS/netbeans
```
or similar and attach the exception output here when you run the node command in NB?

**Comment by vt97john** [comment]
When i run netbeans from the command line i don’t get the error any more.  Makes sense based on what folks have said about the env for a GUI app.  Here’s the log output:

TSService: starting nodejs
TSService: nodes loaded

There are other netbeans plugins that don’t have this issue.  Here is a nodejs plugin that lets you define the path to node in your prefs >> misc:

http://plugins.netbeans.org/plugin/36653/nodejs




John T. Mallonee
Cell: 703-217-7673
Fax: 703.738.7444

Clearsoft Inc.
Software Engineering & Systems Integration
4000 Legato Road | Suite 1100 | Fairfax, VA 22033 |  www.clearsoftinc.com<http://www.clearsoftinc.com/>

PLEASE NOTE:  This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

On Oct 28, 2015, at 6:46 PM, Tim-Hinnerk Heuer <notifications@github.com<mailto:notifications@github.com>> wrote:


Mh, so that should be right then and working. Not sure why it won't for you. Can you execute NetBeans from a terminal:

/Applications/NetBeans/NetBeans\ 8.1\ RC.app/Contents/MacOS/netbeans


or similar and attach the exception output here when you run the node command in NB?

**Comment by geekdenz** [comment]
@jeffrey-easyesi Do you think it's reasonable to require the node js module to be installed for the NBTS plugin and then use its settings?
Or should there be another setting under Misc where one sets the node js path. Or is there something else that makes more sense?

**Comment by geekdenz** [comment]
@vt97john 
Can you run this command in a terminal?
```
echo 'var a = 123; console.log("a=",a);' | /usr/local/bin/node && /usr/local/bin/node -v
```
and post the output? If it outputs 
```
a= 123
vx.x.x
```
it should be working. Otherwise, NetBeans might pick up node or nodejs from the NB environment somehow and getting a wrong executable.

**Comment by mintern** [comment]
I think you're overthinking this, @geekdenz. I'm pretty sure that @vt97john is running the most recent netbeanstypescript.nbm release rather than building the latest plugin from source. As I said above, the /usr/local/bin/node fix has not been included in a prebuilt release yet.

**Comment by mintern** [comment]
Until the next release is packaged, you can start NetBeans from the command line, or build the plugin from source, or correctly set the PATH for GUI apps.

**Comment by vt97john** [comment]
This is correct.


John T. Mallonee
Cell: 703-217-7673
Fax: 703.738.7444

Clearsoft Inc.
Software Engineering & Systems Integration
4000 Legato Road | Suite 1100 | Fairfax, VA 22033 |  www.clearsoftinc.com<http://www.clearsoftinc.com/>

PLEASE NOTE:  This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

On Oct 29, 2015, at 12:47 AM, Brandon Mintern <notifications@github.com<mailto:notifications@github.com>> wrote:


I think you're overthinking this, @geekdenz<https://github.com/geekdenz>. I'm pretty sure that @vt97john<https://github.com/vt97john> is running the most recent netbeanstypescript.nbm release rather than building the latest plugin from source. As I said above, the /usr/local/bin/node fix has not been included in a prebuilt release yet.

**Comment by vt97john** [comment]
OK, thanks.

John T. Mallonee
Cell: 703-217-7673
Fax: 703.738.7444

Clearsoft Inc.
Software Engineering & Systems Integration
4000 Legato Road | Suite 1100 | Fairfax, VA 22033 |  www.clearsoftinc.com<http://www.clearsoftinc.com/>

PLEASE NOTE:  This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

On Oct 29, 2015, at 12:49 AM, Brandon Mintern <notifications@github.com<mailto:notifications@github.com>> wrote:


Until the next release is packaged, you can start NetBeans from the command line, or build the plugin from source, or correctly set the PATH for GUI apps.

**Comment by mintern** [comment]
@jeffrey-easyesi just packaged the latest release:

https://github.com/Everlaw/nbts/releases/tag/v1.6.2.1

This should allow you to use the `/usr/local/bin/node` executable without any issues.

Please reopen this issue if [the latest netbeanstypescript.nbm](https://github.com/Everlaw/nbts/releases/download/v1.6.2.1/netbeanstypescript.nbm) still doesn't work for you.

Thank you for your patience!

**Comment by vt97john** [comment]
That worked, thanks guys.

John T. Mallonee
Cell: 703-217-7673
Fax: 703.738.7444

Clearsoft Inc.
Software Engineering & Systems Integration
4000 Legato Road | Suite 1100 | Fairfax, VA 22033 |  www.clearsoftinc.com<http://www.clearsoftinc.com/>

PLEASE NOTE:  This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

On Nov 2, 2015, at 11:17 PM, Brandon Mintern <notifications@github.com<mailto:notifications@github.com>> wrote:


@jeffrey-easyesi<https://github.com/jeffrey-easyesi> just packaged the latest release:

https://github.com/Everlaw/nbts/releases/tag/v1.6.2.1

This should allow you to use the /usr/local/bin/node executable without any issues.

Please reopen this issue if the latest netbeanstypescript.nbm<https://github.com/Everlaw/nbts/releases/download/v1.6.2.1/netbeanstypescript.nbm> still doesn't work for you.

Thank you for your patience!

**Comment by mcdonnell-john** [comment]
Hi,

I am running NetBeans 8.2 on MacOSX and I am running into this issue.

Any ideas?

**Comment by yavin5** [comment]
I downloaded everything brand new, on MacOS, and I have the same issue.  When I run NB from the command line, it works.

The user expectation is likely to be: If I'm logged into the desktop, and I made my shell change before my login, and I run the IDE, the IDE can find the nodejs executables if my command line shell can, and the IDE defaults to using the same one the shell finds and uses.

Thanks..
