### ISSUE TITLE
Automatic Redeploy when compileOnSave doesnt work

### ISSUE THREAD

**Issue by traugott** [Everlaw/nbts#20]
If a war is deployed and a js file gets created/modified by the compile-on-save-functionality, the newly created/modified file doesn't get deployed.

The reason is the js file gets created by the means of nio. When creating/modifying the file by the means of FileObject, netbeans is aware of the change and deploys the new js file.

I created the following patch for TSIndexerFactory:

    # This patch file was generated by NetBeans IDE
    # It uses platform neutral UTF-8 encoding and \n newlines.
    # This patch file was generated by NetBeans IDE
    # It uses platform neutral UTF-8 encoding and \n newlines.
    --- HEAD
    +++ Modified In Working Tree
    @@ -38,7 +38,7 @@
     package netbeanstypescript;
     
     import java.io.IOException;
    -import java.io.Writer;
    +import java.io.OutputStream;
     import java.net.URL;
     import java.nio.charset.StandardCharsets;
     import java.nio.file.Files;
    @@ -155,10 +155,23 @@
                 System.out.println("Writing " + p);
                 try {
                     Files.createDirectories(p.getParent());
    -                try (Writer w = Files.newBufferedWriter(p, StandardCharsets.UTF_8)) {
    -                    if (writeBOM) w.write('\uFEFF');
    -                    w.write(text);
    +              String jsFilename = name.substring(name.lastIndexOf("/") + 1).replaceAll("ts$", "js");
    +              OutputStream os= null;
    +              FileObject o = fileObject.getParent().getFileObject(jsFilename);
    +              if (o != null) {
    +                os = o.getOutputStream();
    +              } else {
    +                os = fileObject.getParent().createAndOpen(jsFilename);
                     }
    +              try {
    +                if (writeBOM) {
    +                  os.write('\uFEFF');
    +                }
    +                os.write(text.getBytes(StandardCharsets.UTF_8));
    +
    +              } finally {
    +                os.close();
    +              }
                 } catch (IOException e) {
                     String error = "Compile on save: could not write file " + name + "\n" + e;
                     DialogDisplayer.getDefault().notify(

**Comment by jeffrey-easyesi** [comment]
I just tested, and it works for me. Can you supply an example project that exhibits the issue?

**Comment by traugott** [comment]
I tried to show the problem with a small example. In a small example the error wasn't shown. I have a bigger war i cannot provide. There are about a 10-12 ts files in the war.

I deploy the war on wildfly 8.2.0 by selecting "debug". Then i changed a ts file, the js file gets generated but only the ts file got deployed (the js file was still the "old" version).

**Comment by traugott** [comment]
Cannot reproduce anymore, so i close the issue.
