### ISSUE TITLE
Full autocompletion

### ISSUE THREAD

**Issue by idarous** [Everlaw/nbts#22]
Hello,

In netbeans 8.1 we can have a full auto-completion in JS when we begin to type a keyword or a variable for example (To enable it, we have to go to Tools > Options > Editor > Code Completion > Chose JavaScript in Language drop-down list and then in the section "Enable Auto Popup completion windows for" we check "All possible situations".
However on using TypeScript with this plug-in we only have an auto-completion for method and attribute after typing a ".".

Is it possible to have the same option for full auto-completion like we have in JavaScript ?
I think with the full-completion available, netbeans will become one of the best IDE for TypeScript. :)

**Comment by jeffrey-easyesi** [comment]
Implemented in master branch. Note that you can already bring up code completion at any time with ctrl-space.

**Comment by idarous** [comment]
Thank you very much. I want to test the new version of this plugin, how can I compile it from source.
I try to clone the repository and then in the root directory I run "ant" but I have some errors. (I used ant 1.9.6)

PS : I prefer use the auto-completion instead of the completion with ctrl-space.

**Comment by mintern** [comment]
The errors might be related to #13...  Are you using NetBeans 8.1?

Just in case it's something else, I filed #24.

**Comment by jeffrey-easyesi** [comment]
This feature is now in the latest release.

**Comment by idarous** [comment]
Thank you very much. It works perfect as I hope.
