### ISSUE TITLE
Netbeans hangs on save

### ISSUE THREAD

**Issue by timautin** [Everlaw/nbts#25]
Hi,

Thanks for this plugin. I'm trying to use it on an Angular2 project, and it makes Netbeans hangs (from 1sec to several minutes) every time I save a file. Seems like the plugin is ignoring the "exclude" directive of my tsconfig.json, which would make the plugin analysing the 50Mo or so JS files contained in my node_modules folder.

Here is my project architecture (I created a Maven project):
- src
    - main
        - java
            - my Java classes
        - webapp
            - app
                - my TS, Less & HTML files
            - node_modules
            - META-INF
            - package.json
            - tsconfig.json
- pom.xml

 And here is my tsconfig.json:
{
    "compilerOptions": {
        "target": "ES5",
        "module": "commonjs",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false
    },
    "exclude": [
        "node_modules"
    ]
}

Is everything correct? Or must I change something? It would really be great to have project templates (https://github.com/Everlaw/nbts/issues/6).

Note: if I put the "node_modules" folder at the root of the project, the problem seems gone, but Netbeans shows an error at the line:
import { Component, View, bootstrap } from 'angular2/angular2';
Saying "Cannot find module 'angular2/angular2'"

Thanks!

**Comment by jeffrey-easyesi** [comment]
This plugin doesn't support having more than one TypeScript project under one source root (the biggest problem is that there's nothing sensible to do if one file is part of two projects). So right now there will be problems with having the whole angular2 npm package (which includes both definition files and its own source code) under webapp.

I think it should work if you move `node_modules` out, and copy just the definition files into `webapp`:
* bundles/typings/angular2/angular2.d.ts
* bundles/typings/es6-shim/es6-shim.d.ts (for Promise)

**Comment by timautin** [comment]
Thanks for your answer! Seems better, but I don't have the "angular2/bundles/typings/angular2/angular2.d.ts". I only have "angular2/angular2.d.ts", which contains:
export * from './common';
export * from './core';
export * from './profile';
export * from './lifecycle_hooks';
export * from './bootstrap';
export * from './upgrade';
import "./manual_typings/globals-es6.d.ts";

Obviously, if I include this file, it doesn't work. I guess you have an older angular2.d.ts?

**Comment by jeffrey-easyesi** [comment]
Yeah, somehow when I did npm install angular2 I got version 2.0.0-alpha.44, even though .46 was already the latest version at that time.

It seems wrong to include .ts source files in the same package as compiled .js, but I guess that's the norm (angular2 and two of its dependencies "@reactivex/rxjs" and "reflect-metadata" all do it) so nbts needs to be able to deal with this. It shouldn't be too difficult to make the plugin exclude extraneous .ts files in the source tree that aren't part of the project per `tsconfig.json`.

**Comment by timautin** [comment]
Great new, thanks for your work!

**Comment by jeffrey-easyesi** [comment]
This is implemented now in the v1.7.3.1 release.

**Comment by timautin** [comment]
Great!! Seems to be working well, if not I'll reopen and add feedback. Thanks a lot!
