### ISSUE TITLE
Export class with "Cannot compile modules unless the '--module' flag is provided" error

### ISSUE THREAD

**Issue by danielschmitz** [Everlaw/nbts#26]
File index.ts:

```typescript
import {Foo} from "Foo"
var test = new Foo();
```

File Foo.ts
```typescript
export class Foo{
    
}
```
Error:
![captura de tela de 2015-12-04 17-21-51](https://cloud.githubusercontent.com/assets/1509692/11598898/944e74bc-9aab-11e5-8bdf-35cf2455c726.png)

project: 
[ModuleError.zip](https://github.com/Everlaw/nbts/files/52405/ModuleError.zip)

**Comment by jeffrey-easyesi** [comment]
You need to create a [tsconfig.json file](https://github.com/Microsoft/typescript/wiki/tsconfig.json) with the compiler options for your project, including the kind of module you are compiling to:
```json
{
    "compilerOptions": {
        "module": "<module kind>"
    }
}
```
As of 1.7, the supported module kinds are "commonjs", "amd", "system", "umd", and "es6". You'll need to put in the kind of module used by the loader or build system that consumes your .js files.

**Comment by danielschmitz** [comment]
Thank you!
