### ISSUE TITLE
Support for <editor-fold> tag

### ISSUE THREAD

**Issue by timautin** [Everlaw/nbts#27]
I'm not sure if this is a Netbeans bug or if this is something the plugin should / could handle. In some languages (eg Java), Netbeans offers the possibility to add code regions, with the <editor-fold> tag. For example:

// &lt;editor-fold desc="GUI events"&gt;

... some code

// &lt;/editor-fold&gt;

Then this code region can be folded (like functions can). But this doesn't work with nbts. Can you tell me if this is the plugin's role to handle that, or if I have to fill a bug to the Netbeans team? Thanks!

**Comment by jeffrey-easyesi** [comment]
Implemented in v1.7.5.0

**Comment by timautin** [comment]
Thanks for your reactivity, but doesn't seem to work (same behaviour as before the update).

**Comment by jeffreymorlan** [comment]
Looks like TypeScript's folding of multiple consecutive `//` comments immediately before a declaration is interfering.

**Comment by jeffrey-easyesi** [comment]
Looks like TypeScript's folding of multiple consecutive `//` comments immediately before a declaration is interfering.

**Comment by timautin** [comment]
I don't think so, this doesn't work either:


    import { ElementRef } from 'angular2/angular2'

    export class Widget {

        // <editor-fold desc="Attributes">

        protected m_element: ElementRef;

        // </editor-fold>



        // <editor-fold desc="Constructor">

        constructor(_element: ElementRef) {

            this.m_element = _element;
        }

        // </editor-fold>
    }

**Comment by timautin** [comment]
But indeed, this is working:

    import { ElementRef } from 'angular2/angular2'

    export class Widget {

        // <editor-fold desc="Attributes">

        protected m_element: ElementRef;

        // </editor-fold>
    }

Will you work on a fix?

**Comment by jeffrey-easyesi** [comment]
Workaround implemented in v1.7.5.1. Your example should now fold properly (with or without the // ------ comments)

**Comment by timautin** [comment]
This time it's working, thanks!!
