### ISSUE TITLE
Support projects  Java Web -> Web Application

### ISSUE THREAD

**Issue by logongas** [Everlaw/nbts#29]
Support plugin in projects "Java Web" -> "Web Application"

**Comment by jeffrey-easyesi** [comment]
The plugin should work with .ts files in any kind of project.

Are you talking about the Project Properties category with the compile-on-save option in it? I made it appear in all the same kinds of projects that have the parent category "JavaScript Frameworks", but it looks like (non-Maven) Web Application is not one of those.

**Comment by logongas** [comment]
Yes, is the "compile-on-save option" in "Java Web" -> "Web Application" projects.

**Comment by jeffrey-easyesi** [comment]
Fixed in master branch. In the meantime you can always enable it manually by putting
`auxiliary.netbeanstypescript.compileOnSave=true`
in nbproject/project.properties

**Comment by logongas** [comment]
Thank you :-)

**Comment by jeffrey-easyesi** [comment]
Fixed in release 1.8.2.0
