### ISSUE TITLE
Only works with .ts extensions

### ISSUE THREAD

**Issue by Tiinusen** [Everlaw/nbts#30]
I have started using this plugin for my ES projects with babel.

It would be great if this plugin supported adding of file extensions more than just ".ts". 

I tried just creating a new one through Tools --> Options --> Files with "text/typescript" as MIME.

Syntax highlightning works but I get an alert at top of the editor window that states the following
"File {src/main.es} is not in project defined by tsconfig.json".

But if i rename it to ".ts" no alert message is shown.

Is there a workaround in tsconfig.json or is this a plugin issue?

**Comment by jeffrey-easyesi** [comment]
This is unrelated to the plugin; [TypeScript won't include source files with arbitrary extensions in a project](https://github.com/Microsoft/TypeScript/issues/2302). You can see this error by compiling from the command line:
>$ tsc src/main.es 
>error TS6054: File 'src/main.es' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

**Comment by Tiinusen** [comment]
I see, Thanks for the quick response
