### ISSUE TITLE
No code completion for import modules

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#31]
When I type this:

import \* as IEnumerable from ', I expected that when I type ' that the code completion for the modules/files comes up but there isn't any code completion for this.
It should shows me the available modules maybe from the namespace/folder or whatever and when I type ./ all in this folder or ../ in the parent folder and so on. WebStorm shows me all available modules inside the folder or from the namespace I don't know. And it works for ../ as expected and mentioned from me.

Regards

Chris

**Comment by jeffrey-easyesi** [comment]
This is something that should be implemented in the TypeScript language service: https://github.com/Microsoft/TypeScript/issues/188

**Comment by codecoster** [comment]
Any chances to bring this to work in nbts plugin anyways?
Other IDE's support this and I think it is a really helpful and important feature.

**Comment by Chris2011** [comment]
The problem is to wait until this is coming to the official TS repo. This issue is open since 2014... It would be nice to handle such things separately from the official repo.

**Comment by jeffrey-easyesi** [comment]
Import completion was recently merged into TS's `master` and `release-2.0.5` branches: https://github.com/Microsoft/TypeScript/pull/9353 https://github.com/Microsoft/TypeScript/pull/10692

**Comment by jeffrey-easyesi** [comment]
2.0.5 supports this but I need to add some glue code

**Comment by Chris2011** [comment]
Very nice, works as expected. One little thing, that would make more fun is to add a dot "." after each namespace/module. This is what the java editor does and it is very handy.

You write or -> Code completion comes up, you choose "org" and hit enter and instead of org there is org. and the new code completion comes up immediately so you can choose the next module and the next, until you are at the end of your module. That would be cool to have it there too, please add it. :)

**Comment by jeffrey-easyesi** [comment]
Fixed in 2.0.5.1.
I made it add a slash when completing a directory name, but I could not find a way to make it automatically bring up completion again like the Java editor does (the Java editor itself does not use CSL APIs like CodeCompletionHandler, so it's not very useful as a reference for writing plugins).

**Comment by Chris2011** [comment]
For strings is kind of ok, what was the reason to not the same for the dot notation like System.Collections.Generic.IEnumerable (For example, my use case tu import modules)?

**Comment by Chris2011** [comment]
For the other Problem, that the code completion not comes up, I can create a new bug or we can leave it open, as you want.

**Comment by jeffrey-easyesi** [comment]
For internal modules (namespaces), each level is itself a module so the code completion can't know where you want to stop:
```ts
namespace System.Collections.Generic.IEnumerable {}
// all four of these are valid:
import S = System;
import C = System.Collections;
import G = System.Collections.Generic;
import I = System.Collections.Generic.IEnumerable;
```

For external modules, regarding having the completion come up again after completing a directory - do you have an example of a plugin built on CSL (i.e. pretty much any language plugin except Java) that does that?

**Comment by Chris2011** [comment]
Ok I understand, I will have a talk to another developer who can help here maybe with automatic opens the code completion.
