### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#32]
I have this piece of code:

```
import * as IEnumerable from 'IEnumerable'
```

in my file, which is located in folder System -> Collections -> Generic and is called List.ts.
IEnumerable.ts is located inside System -> Collections -> Generic -> Interfaces.

Webstorm can find this module, the netbeans plugin not. It is red and shows me the message: Cannot find module 'IEnumerable'.

Regards

Chris

**Comment by jeffrey-easyesi** [comment]
I tried compiling that from the command line using `tsc` and got the same error. What happens when you compile from the command line? If it works please post your `tsconfig.json` file.

**Comment by Chris2011** [comment]
You are right, it is not working. I tried this:

```
tsc --target es6 --module es6 -noEmitOnError List.ts
```

inside System/Collections/Generic and it says the same BUT, when I change the line from:

```
import * as IEnumerable from 'IEnumerable';
```

to

```
import * as IEnumerable from '/Interface/IEnumerable';
```

and I got the same. I added my project to the ticket.
[TypescriptTest.zip](https://github.com/Everlaw/nbts/files/100604/TypescriptTest.zip)

**Comment by jeffrey-easyesi** [comment]
The syntax for a relative import is `from './Interface/IEnumerable'` (note leading dot). But that still won't work, because your IEnumerable.ts is a global file with internal modules, and `import` requires an external module. (See http://www.typescriptlang.org/Handbook#modules for details about the different kinds of modules.)

Anyway, if the project doesn't build with tsc, then nbts showing an error is correct (and WebStorm is incorrect for not showing it).

**Comment by Chris2011** [comment]
Ok, I understand and now it works, thx :). So what will be the best solution to handle modules with namespaces as you can see it in my example? only folder structure and the IEnumerable should have the export interface or the example what you see in my code?

Ok I understand that webstorm will do it wrong.

**Comment by Chris2011** [comment]
Ok I got a good thing:

```
import IEnumerable = System.Collections.Generic.IEnumerable;
```

And I have to add the keyword declare infront of the module inside the IEnumerable.ts file. So I will close this ticket. Thx for the help.

**Comment by Chris2011** [comment]
I have the same problem with this repo: https://github.com/pkozlowski-opensource/ng2-play. This is a angular2 example with TypeScript. I cloned the repo, did npm install and I open the hello.ts file and got the error for these 2 imports:

```
import {Component} from 'angular2/core';
import {bootstrap} from 'angular2/platform/browser';
```

Error: Cannot find module: 'angular2/core'
Error: Cannot find module: 'angular2/platform/browser'

but when I call the gulp ts2js task or the play task, everything is fine. The App compiles and started and worked.

**Comment by Chris2011** [comment]
Same happened for this project: https://github.com/johnpapa/angular2-go

**Comment by jeffrey-easyesi** [comment]
Both projects open fine for me. Can you confirm the files node_modules/angular2/core.d.ts and node_modules/angular2/platform/browser.d.ts exist, and are visible in NetBeans?

**Comment by Chris2011** [comment]
Ok thx, the problem was that I ignored the node_modules folder and the bower_components folder, but I have a good reason why I did this and why I will do this again. Because I always opened NB with multiple projects. So Sometimes 5, sometimes 10, it depends. Often I close unused projects for a while. And when I have to index the node and bower folder, this is a pain in the ass while using Go To File and Go To Whatever. node_modules and bower_components have really a lot of files like > 1000 or > 10k. So than I have to indexing 50k files and often duplicates when I search for example "core" or "main", common phrases inside file names, I see a big list of results where I have to choose the right file for this.

So because of that, I ignored node_modules and bower_component files from the index and I were really lucky. Better performance and so on. So I can't change this option back and I don't want to. Is there another solution for this problem?

**Comment by jeffrey-easyesi** [comment]
In the latest release (1.8.10.0) you can now reference or import .ts files that are outside the source root or in an ignored directory.

**Comment by Chris2011** [comment]
Great :)

**Comment by Chris2011** [comment]
I tried it with the project that I mentioned and it worked now, no error anymore, but jumpto doesn't work.

**Comment by Chris2011** [comment]
Code completion for the references is the same problem as this ticket: https://github.com/Everlaw/nbts/issues/31, right?

**Comment by jeffrey-easyesi** [comment]
Go-to-declaration to non-indexed files works since 1.8.10.2.
