### ISSUE TITLE
Please improve code completion

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#33]
When I'm in the first line and hit "i" I expect that the first item what will be found is import, but I got a list of lots of other stuff, started by innerHeight, innerWidth, indexedDB etc, pp. In WebStorm you can see a better behaviour. It shows you a lot of more stuff too but the first item is always import, because of the context. The same should happen for module, export, extends, implements, class, private, public. etc. Because in this context, no other stuff make sense.

Regards

Chris

**Comment by jeffrey-easyesi** [comment]
`innerHeight` etc are visible as global variables. It's not very common to assign to them, but it is legal.

The list of code completion items is provided by the TypeScript language service, so if it works but you're not happy with the list, you'll need to take it up with the TypeScript project itself (https://github.com/Microsoft/TypeScript/)

**Comment by Chris2011** [comment]
In webstorm it works as expected, so as that what I want why is this an external thing?

**Comment by jeffrey-easyesi** [comment]
Webstorm is the only TypeScript IDE I know of that doesn't use the language service from the TypeScript project; they wrote their own implementation of everything.

**Comment by Chris2011** [comment]
Ok I see, thx for the info. Make sense but this is more work. Ok so typescript has to implement some logic that the nbts plugin can use this better.
