### ISSUE TITLE
Please create the tsconfig.json file from the project properties.

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#34]
I really would like to contribute, but atm, I don't have enough time to do so. But it should be not a big deal to bring all options from the tsc compiler to the TSProjectCustomizer and to save it to a project specific tsconig.json file.

So that I can check/uncheck noEmitOnError or set/change the target  version between es3, es5 and es6.

Regards

Chris

**Comment by jeffrey-easyesi** [comment]
The problem with having a GUI editor for a human-readable file format like tsconfig.json is that it would destroy any formatting or comments in the file. I think what would be best is if the plugin implemented special support for editing tsconfig.json as text, with error checking, and code completion of option names and values. Mockup:

![tsconfig-editor-mockup](https://cloud.githubusercontent.com/assets/3847609/13479597/f54ed7ee-e08c-11e5-9e32-15f8f198c44d.png)

**Comment by Chris2011** [comment]
With the formatting, I understand the problem. For the problem with comments in json files, json doesn't support comments, so this is not a problem. Maybe it would be better to replace the values for each option which were found. I created a fork and you can see here the progress, but it's work in progress and atm, I don't have time to investigate.

The other thing is with compileOnSave, this is an option inside the tsconfig.json file, but you use it and save it as a project property, are there any conflicts with compileOnSave inside tsconfig and yours? I mean if you set it on true and I set it on false inside the tsconfig file, which option will win?

**Comment by Chris2011** [comment]
https://github.com/Chris2011/nbts/blob/master/src/netbeanstypescript/TSProjectCustomizer.java what I want is all options in the TsProjectCustomizer. You can see the progress that I did. I know the problem with the formatting too, and maybe there is a solution to only replace the options inside the file.

**Comment by jeffrey-easyesi** [comment]
> With the formatting, I understand the problem. For the problem with comments in json files, json doesn't support comments, so this is not a problem.

Standard JSON does not allow comments but [tsconfig.json does](https://github.com/Microsoft/TypeScript/pull/5450)

> The other thing is with compileOnSave, this is an option inside the tsconfig.json file, but you use it and save it as a project property, are there any conflicts with compileOnSave inside tsconfig and yours? I mean if you set it on true and I set it on false inside the tsconfig file, which option will win?

`compileOnSave` in tsconfig.json was not standardized until 1.8. I haven't implemented support for it yet; when I do it will override the project setting (I'll probably deprecate the project setting; it's less flexible since there may be multiple tsconfig.json projects within one NetBeans project)

**Comment by Chris2011** [comment]
if we can have multiple tsconfig files in one NB project, than maybe we need an other solution. I thought that the tsconfig file is like the package or bower json file, and usually you only have one file per project. If you have subfolders with those files, netbeans will accept them as new "html5 projects", where we have other project options. Maybe you should use tsconfig files to identify them as ts projects / ts subprojects too(?). Only an opinion. If there isn't a nice solution, then yeah you are right, that we should change the options manually. I will have a look at webstorm, how they do that.

**Comment by Chris2011** [comment]
Ok, I understand, that doesn't make sense after researching a bit. Multiple tsconfig files inside one nb project, is really hard to handle. I will cancel the work. I like the thing with code completion for the options inside the tsconfig file. This would be handy. Thx for your info.

**Comment by jeffrey-easyesi** [comment]
tsconfig.json editor is now implemented (plugin version 1.8.10.3).

**Comment by Chris2011** [comment]
It's working for me so we can close this ticket :). Thx for the work.
