### ISSUE TITLE
No .nbm file

### ISSUE THREAD

**Issue by snowyurik** [Everlaw/nbts#36]
Ok, I can create it from sources, but I know, you already have it. Why don't you publish it? Or at least single .jar file?

**Comment by mintern** [comment]
https://github.com/Everlaw/nbts/releases

**Comment by snowyurik** [comment]
Thank you very much ) just FYI: some people in netbeans repository also ask similar questions http://plugins.netbeans.org/plugin/60605/typescript-editor

**Comment by mintern** [comment]
Thanks for the heads-up. Best wishes!

**Comment by 98abhinav** [comment]
thanks for help :)
