### ISSUE TITLE
Can't open TypeScript files; weird MIME-type

### ISSUE THREAD

**Issue by alexschrod** [Everlaw/nbts#37]
In my options, ts files are set to a MIME-type called "text/qttranslation+xml". This is the default, apparently, as you can see by the "Default" button being grayed out:
![image](https://cloud.githubusercontent.com/assets/767490/13375730/dc3f5644-dda7-11e5-99bd-ce5f29c156f4.png)

Attempting to open any .ts files with this MIME-type set just makes nothing happen. Also, the icon the files have is weird:
![image](https://cloud.githubusercontent.com/assets/767490/13375741/0d173e3a-dda8-11e5-89ee-078c5a435302.png)

I've looked through the list of MIME-types presented to me; none of them seem to have anything to do with TypeScript. If I override the default MIME-type with "text/javascript", I can open the files, but they're clearly being treated as regular Javascript files if I do that. Which MIME-type should I set to get the TypeScript editor to work?

**Comment by jeffrey-easyesi** [comment]
If the plugin is installed, `text/typescript` should be an option:
![screenshot from 2016-03-01 10 02 59](https://cloud.githubusercontent.com/assets/3847609/13436603/e6900294-df94-11e5-94b3-cbc9b7a210f2.png)

**Comment by alexschrod** [comment]
I'm sorry, I made an oversight. The plugin had only made its way into the "downloaded" list, not the "installed" list. And it turns out, each time I try to install it and restart Netbeans, it keeps not actually getting installed. I assume this is a problem with Netbeans or my system, and not your plugin. Sorry for the false flag. :)
