### ISSUE TITLE
Better integration with Netbeans theme Darcula

### ISSUE THREAD

**Issue by idarous** [Everlaw/nbts#39]
Hello,

JavaScript and JSON codes are very pretty when using the Netbeans theme Darcula as you can see.

![capture du 2016-03-06 12 43 15](https://cloud.githubusercontent.com/assets/15747854/13553910/4ec79950-e399-11e5-9df0-46306433ab72.png)

However, TypeScript code is not very pretty when using the theme Darcula. For example methods of classes are displayed in black and some identifiers are displayed in purple and it's difficult to read them.

![capture du 2016-03-06 12 53 13](https://cloud.githubusercontent.com/assets/15747854/13553935/3c09e7ea-e39a-11e5-8950-14c28263d5c8.png)

Is it possible to improve colours displayed in TypeScript files when using Darcula theme ?

**Comment by jeffrey-easyesi** [comment]
You can change the colors for any theme/language combination in Tools > Options > Fonts & Colors.

There's no way for all the language-specific syntax categories, like global variables (purple) to automatically look good for any third-party theme one might install. I can fix method declarations though - those are not language-specific so they could inherit from the theme's generic method/class colors.

**Comment by idarous** [comment]
Ok thank you, I forgot that I colors for TypeScript code can be easily changed using Tools > Options > Fonts & Colors.
I've changed the colors for global variables and methods in order to have a code more readable.

I close this issue.
