### ISSUE TITLE
Utf-8 encoding onsave

### ISSUE THREAD

**Issue by Zefling** [Everlaw/nbts#41]
Hi,

I have a little problem with the compilation onsave and UTF-8 files. For example, with a simple test.ts: 
```typescript
let test = "Déjà-vu";
```

The compiled file test.js was badly encoded:
```typescript
 var test = "DÃ©jÃ -vu";
 //# sourceMappingURL=test.js.map﻿
```
I do not have this problem with a command line compilation.

**Comment by jeffrey-easyesi** [comment]
The plugin's compile-on-save should always output in UTF-8, same as `tsc` does. Can you give a hex dump of the source file, the output from compile-on-save, and the output from `tsc`?

**Comment by Zefling** [comment]
My test.ts : 
`6c 65 74 20 74 65 73 74 20 3d 20 22 44 c3 a9 6a c3 a0 2d 76 75 22 3b 0a 0a 0a`

With tsc :
`76 61 72 20 74 65 73 74 20 3d 20 22 44 c3 a9 6a c3 a0 2d 76 75 22 3b 0d 0a 2f 2f 23 20 73 6f 75 72 63 65 4d 61 70 70 69 6e 67 55 52 4c 3d 74 65 73 74 2e 6a 73 2e 6d 61 70  `

With compile-on-save :
`76 61 72 20 74 65 73 74 20 3d 20 22 44 c3 83 c2 a9 6a c3 83 c2 a0 2d 76 75 22 3b 0d 0a 2f 2f 23 20 73 6f 75 72 63 65 4d 61 70 70 69 6e 67 55 52 4c 3d 74 65 73 74 2e 6a 73 2e 6d 61 70`

**Comment by dipacs** [comment]
I have the same problem too.

**Comment by jeffrey-easyesi** [comment]
I just fixed a bug that could cause this, can you try in version 1.8.10.1?

**Comment by Zefling** [comment]
It seems good. :+1:
