### ISSUE TITLE
Always show " Cannot compile modules unless the '--module' flag is provided. "

### ISSUE THREAD

**Issue by snipking** [Everlaw/nbts#46]
But I've set "module":"commonjs" in tsconfig.json, and no error when run tsc in command line.

**Comment by jeffrey-easyesi** [comment]
Make sure tsconfig.json is somewhere where the NetBeans indexer can find it. If you're not sure, try creating a .ts file in the same directory, and opening it - if the plugin reports an "unknown source root" error, that directory isn't indexed.

**Comment by snipking** [comment]
Here's my project structure:
```
.
├── bower.json
├── gulpfile.js
├── nbproject
├── node_modules
├── package.json
├── src
│   ├── bower_components
│   ├── css
│   ├── index.html
│   ├── pages
│   ├── scripts
│   └── typings
├── test
├── tsconfig.json
├── tsd.json
├── webpack.config.js
└── dist
```
If I put the tsconfig.json into the 'src' folder, the error is gone. Is there anyway I can config the indexer's searching path ?

**Comment by jeffrey-easyesi** [comment]
Not that I know of. Currently tsconfig.json must be under a source root. Previous issue: https://github.com/Everlaw/nbts/issues/21
