### ISSUE TITLE
TS1.8.5 - Go To Declaration and Find Usage is not working in Netbeans8.1?

### ISSUE THREAD

**Issue by katturajam** [Everlaw/nbts#47]
I am tryning function to go declartaion and find uasage but it is not working.

**Comment by jeffrey-easyesi** [comment]
They both work for me. Can you be more specific?

**Comment by katturajam** [comment]
@jeffrey-easyesi  Is it work in netbeans?

**Comment by jeffrey-easyesi** [comment]
Yes, in netbeans 8.1. Do you have an example of a TypeScript file or project where they don't work?

**Comment by katturajam** [comment]
Current release of 1.8.10.1 typescript is working good. No Problem. Thanks
