### ISSUE TITLE
Please add feature to fix imports

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#49]
In Java you have a feature when you have this:

```
class Test extends BaseTest implements ITest {
}
```

if you haven't import the right package for BaseTest or ITest yet, you can hit Alt + Enter and you got the  hint functionality "Add package: org.foo.bar.BaseTest."

This feature would be very handy for TypeScript too, that he can find any module where ITest and BaseTest is declared or exported and show the hint which import you want to use.

Cheers

Chris

**Comment by Chris2011** [comment]
As you can see it here: http://blog.jetbrains.com/webstorm/2016/04/angular-2-workflow-in-webstorm/#ng2-imports

this is exact what I would like to see in this plugin. Imports are resolved while adding the @Component code snippet to the source code. And for other Components like self written or so, it would be great to see the error: "Can't find module myModule" and when I hit alt + enter I got the hints where I can say: "Add Import Comp.myModule" or smth like that. Fix imports is in Java working as well.

**Comment by everflux** [comment]
That would be a great help indeed.

**Comment by jeffrey-easyesi** [comment]
"Quick fix" functionality like this is something that belongs in the TypeScript language service, so that all plugins based on that could use it.

See: https://github.com/Microsoft/TypeScript/issues/6943

**Comment by jeffrey-easyesi** [comment]
This has been implemented in the TypeScript project and will be in version 2.2: https://github.com/Microsoft/TypeScript/pull/11768

**Comment by Chris2011** [comment]
Works super. Not perfect but for this little misbehaviour I will create a new ticket :)
