### ISSUE TITLE
Require code completion in ts files is broken

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#50]
In a js file for node, I have:

```
var properties = require('');
```

and when I hit ctrl + space inside '' I got the code completion to find default packages like fs or ./myPackage. In my case I added a npm package called properties to interact with property files. In node everything is fine, I have the code completion but in a ts file, there is no code completion to find packages. This is a must have in my opinion to find certain packages after hitting ctrl + space.

Regards

Chris

**Comment by jeffrey-easyesi** [comment]
https://github.com/Everlaw/nbts/issues/31
https://github.com/Microsoft/TypeScript/issues/188
