### ISSUE TITLE
Ubuntu 16.04 - Netbeans8.1 - Typescript navigator is not working?

### ISSUE THREAD

**Issue by katturajam** [Everlaw/nbts#51]
I am using Ubuntu 16.04 & Netbeans-8.1. 
I have installed typescript plugin v1.8.10.1 but TS function navigator is not working. 
Can you fix this?

**Comment by jeffrey-easyesi** [comment]
It works fine for me:
![screenshot from 2016-05-24 13 07 10](https://cloud.githubusercontent.com/assets/3847609/15518201/875e77a2-21b0-11e6-8cc2-15980bd69c38.png)
Please be more specific; how is it not working?

**Comment by everflux** [comment]
Do you mean the 'navigator' window or 'navigate' (like "go to declaration" or ctrl-click) ?

**Comment by jeffrey-easyesi** [comment]
Closing due to lack of information.
