### ISSUE TITLE
tyescript and unexpected token

### ISSUE THREAD

**Issue by pirosoft** [Everlaw/nbts#53]
Hi, i have installed plugin to develop with typescript, it's all ok, i can compile in js, i can debug, etc..
But in typescript file the ide give me a error, and i don't understand why, can you help me?
I can run the application without problem, but why i have this error!?!?!

thanks
the error image:
https://dl.dropboxusercontent.com/u/3159474/typescript.jpg

**Comment by bokc** [comment]
Look at your tsconf.json file.

**Comment by pirosoft** [comment]
i have tsconfig.json with:
{
    "compilerOptions": {
        "target": "ES5",
        "module": "amd",
        "sourceMap": true,,
        "watch":true,
        "compileOnSave": true
    }
i have copied from a book, it's incorrect?
}

**Comment by Chris2011** [comment]
```json
......"sourceMap": true,, "watch...
```

there are 2 commas, please remove one of them after true.

**Comment by pirosoft** [comment]
sorry, a error of copy, but the error remains...
`{
    "compilerOptions": {
        "target": "ES5",
        "module": "amd",
        "sourceMap": true,
        "watch":true,
        "compileOnSave": true
    }
}`

**Comment by pirosoft** [comment]
sorry, a error of copy, but the error remains...
{ "compilerOptions": { "target": "ES5", "module": "amd", "sourceMap": true, "watch":true, "compileOnSave": true } }

**Comment by Chris2011** [comment]
compileOnSave is not a property of compilerOptions. It should be on the same level as compilerOptions and not a child of it. Please see here for the syntax: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html and search for compileOnSave.

**Comment by pirosoft** [comment]
great! thanks.
i'm newbie on typescript, so to compile .ts file on save i use this option in project properties:
https://dl.dropboxusercontent.com/u/3159474/tscompile.PNG
now i try to use the correct compileOnSave option. 
Thanks again!

**Comment by Chris2011** [comment]
No problem. Please close it :) Thx.
