### ISSUE TITLE
TypeScript Compilation Errors do not Show in NetBeans

### ISSUE THREAD

**Issue by pondrejka** [Everlaw/nbts#55]
We are using TypeScript in NetBeans with Oracle JET.
It mostly works fine for us with this NetBeans plugin.

It automatically compiles our ts files to js. However, I don't see any console about compilation errors.

If I start tsc -w in a separate console then I do see the log messages. But that means the compilation starts from both NetBeans and console.

How can I fix this?

Thanks,
Peter

**Comment by jeffrey-easyesi** [comment]
Errors are shown in the IDE like with every other language, not on compilation.

**Comment by pondrejka** [comment]
Errors shown in the IDE are easily missed. Ideally, we should have a console showing any compilation errors, or even if there are no errors, for track records.

**Comment by jeffrey-easyesi** [comment]
Files with errors in them have a red "!" badge on their icon in the Projects or Files tree, as do their containing folders, making them easy to find:
![error-badges](https://cloud.githubusercontent.com/assets/3847609/17711346/1b6d4360-63a6-11e6-89bb-1456d754b215.png)

You can also see all errors in the Action Items window (clicking on one will bring you directly to the error location in the file):
![action-items](https://cloud.githubusercontent.com/assets/3847609/17712480/f9b9696a-63aa-11e6-8435-0d17901d0cee.png)

**Comment by pondrejka** [comment]
Thanks for the clarification.
Peter

Bringámról küldve
