### ISSUE TITLE
Nbts ready for TypeScript 2?

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#59]
I saw some new features in TS 2, like nullable types, readonly properties, etc. (You can find the full roadmap here: https://github.com/Microsoft/TypeScript/wiki/Roadmap). So my question is, is nbts ready for the most default features in TS2? Some features should only give some errors, which I think will be available out of the box. Maybe there is some token enhancements.

This ticket is only a hint to be aware of TS 2 and 2.1 (but mostly 2.0)

Regards

Chris

**Comment by javatlacati** [comment]
Waiting for TS generators! :sob:

**Comment by Devidian** [comment]
Any Status/Progress updates ? NB is my Favourite IDE currently and i started a new Meteor/Angular2 Project that is already using TS2, all those "errors" displayed are confusing ;)

**Comment by jeffrey-easyesi** [comment]
https://github.com/Everlaw/nbts/releases/tag/v2.0.5.0
Some of the new config features may not work yet (I know `lib` doesn't); this will be fixed in a follow-up release.
