### ISSUE TITLE
Delete previous word is not working for spaces.

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#68]
There is a shortcut called "Delete previous word". With this you can delete a whole word with ctrl + back_space which is very cool. In all languages, except TypeScript, you can delete more than one spaces too.

If you have spaces after a word like ... (Dots represent spaces) or you have indentaion

{
...private
......whatever
...
}

you can ctrl+back_space and all spaces are gone from the line. This is a pain in the ass, I have to delete all spaces, one by one. Please add this missing feature into the TypeScript editor.

Cheers

Chris

**Comment by Chris2011** [comment]
I created a little screen capture for you: 
![deletepreviousword](https://cloud.githubusercontent.com/assets/795658/18389292/a02afe96-76a5-11e6-9fa2-270e4bc4c6a8.gif)

**Comment by jeffrey-easyesi** [comment]
Fixed in master

**Comment by Chris2011** [comment]
Great, thx. :)

**Comment by jeffrey-easyesi** [comment]
Fix released in 2.0.5.0
