### ISSUE TITLE
Standard libraries not found (TypeScript 2)

### ISSUE THREAD

**Issue by RomkeVdMeulen** [Everlaw/nbts#69]
I've switched to TypeScript 2 and dropped a couple of dependencies from my `typings`. In stead I now have this in my `tsconfig`:

```
    "lib": ["es2015", "es2016", "dom"]
```

Since the switch, though `tsc` can compile my sources just fine, my Netbeans editor is giving lots of errors like `Cannot find name 'Promise'` or `Cannot find name 'Object'`. Have I missed something?

**Comment by jeffrey-easyesi** [comment]
Fixed in 2.0.5.1.
BTW, "es2016" includes "es2015" so you only need `"lib": ["es2016", "dom"]`

**Comment by RomkeVdMeulen** [comment]
Thanks for the tip!
