### ISSUE TITLE
Compile On Save

### ISSUE THREAD

**Issue by geekdenz** [Everlaw/nbts#7]
When a TS file is saved, it would be convenient if the user had the ability to automatically compile *.ts files. This could be a project wide and/or IDE wide setting as well.

Geertjan already did something like this that could be adapted and improved to fit better into this project.

**Comment by geekdenz** [comment]
Just read that compiling can be done incrementally and that it is faster when a process keeps running instead of executing tsc for every save for every file. This is intuitive and what one would expect and fits well in the way this module is implemented.

**Comment by jeffrey-easyesi** [comment]
I've already started on this and should have it done pretty soon.

**Comment by geekdenz** [comment]
Looks good and works well! Good work! Even with tsconfig.json in the site root.
