### ISSUE TITLE
Modules are mixed with code templates for import

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#86]
As you can see it in my image, when I hit ctrl + enter inside the string, I see modules and code templates:

![imports-with-code-templates](https://cloud.githubusercontent.com/assets/795658/22143267/c3f9541e-def9-11e6-839c-c30a6f456abc.png)

For imports and the module stuff, I only expect module related code and not everything.

**Comment by Chris2011** [comment]
Same for your own module folders:

![imports-with-code-templates-2](https://cloud.githubusercontent.com/assets/795658/22143392/2b7ca5e6-defa-11e6-80b1-ba1a91a2b27f.png)


and the worst thing is for your own modules inside the folders, they will add to the end and not to the beginning:

![imports-with-code-templates-3](https://cloud.githubusercontent.com/assets/795658/22143411/3fbdaaaa-defa-11e6-8a5f-805347690b4a.png)

**Comment by jeffrey-easyesi** [comment]
I think I can fix this by implementing a `CodeTemplateFilter.Factory`

**Comment by jeffrey-easyesi** [comment]
Fixed in 2.1.5.0

**Comment by jeffrey-easyesi** [comment]
argh, the "fix" broke the ability to use code templates with the tab key

**Comment by Chris2011** [comment]
Ok I will try, thx. Yes I noticed the problem too.

**Comment by Chris2011** [comment]
Works well.
