### ISSUE TITLE
code templates are not working 

### ISSUE THREAD

**Issue by dilotec-2015** [Everlaw/nbts#91]
code templates are not working on typescript files.

netbeans 8.2
typescript editor 2.1.5.0

**Comment by Rycochet** [comment]
https://github.com/Everlaw/nbts/releases

This is on to 2.1.5.3 - and two of those releases are specifically addressing the templates (both of which are over two weeks old)...

**Comment by dilotec-2015** [comment]
Thank you very much ☺

Von: Rycochet [mailto:notifications@github.com]
Gesendet: Donnerstag, 16. Februar 2017 11:44
An: Everlaw/nbts <nbts@noreply.github.com>
Cc: Waldemar Scholtyssek <W.Scholtyssek@dilotec.de>; Author <author@noreply.github.com>
Betreff: Re: [Everlaw/nbts] code templates are not working (#91)


https://github.com/Everlaw/nbts/releases

This is on to 2.1.5.3 - and two of those releases are specifically addressing the templates (both of which are over two weeks old)...
