### ISSUE TITLE
Netbeans 8.2 and errors in file

### ISSUE THREAD

**Issue by Valantir007** [Everlaw/nbts#95]
Hi, I installed netbeans 8.2, typescript 2.1.5 and this plugin version 2.1.5.3. When I open file like this:

```
class Test {
    protected prefix: string; 
}
```

I got errors in line 2 and 3:

line 2) Expected ; but found prefix protected prefix: string; 
line 3) Expected eof but found }

Anyone can help me?

**Comment by jeffrey-easyesi** [comment]
Make sure the file has a .ts extension, not .js

**Comment by Valantir007** [comment]
Yes, file has .ts extension

**Comment by Valantir007** [comment]
Screens of errors:
http://i67.tinypic.com/6qefc2.jpg

**Comment by Chris2011** [comment]
It seems that you switched the mimetype for ts files to js. Go to options -> misc -> Files and choose typescript in both lists

**Comment by Valantir007** [comment]
Yes, it fixed my problem. Thx :)
